version: '3.8'

services:
  # AgentMoby Security Dashboard - The main UI
  agentmoby-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    hostname: agentmoby-dashboard
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://agent-core:8000
      - MCP_GATEWAY_URL=http://mcp-gateway:8811
      - NODE_ENV=production
    depends_on:
      - agent-core
      - mcp-gateway
    networks:
      - agentmoby-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # AgentMoby Core Agent - The AI brain with security focus
  agent-core:
    build:
      context: .
      dockerfile: Dockerfile.agent-core
    hostname: agent-core
    ports:
      - "8000:8000"
    environment:
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/sse
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - AI_DEFAULT_MODEL=openai/gpt-4
      - NODE_ENV=production
      - AGENT_ROLE=security_analyst
      - SECURITY_MODE=enabled
    depends_on:
      - mcp-gateway
      - security-db
    secrets:
      - openai-api-key
    networks:
      - agentmoby-network
      - security-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MCP Gateway - Secure tool management
  mcp-gateway:
    image: docker/mcp-gateway:latest
    hostname: mcp-gateway
    ports:
      - "8811:8811"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    user: "0:0"
    command:
      - --transport=sse
      - --servers=fetch,brave,resend,curl,mongodb
      - --config=/mcp_config
      - --secrets=docker-desktop:/run/secrets/mcp_secret
      - --verbose
    configs:
      - mcp_config
    secrets:
      - mcp_secret
    depends_on:
      - security-db
    networks:
      - agentmoby-network
      - security-network
    restart: unless-stopped
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  # Security Database - Store agent logs, threats, etc.
  security-db:
    image: mongo:7-jammy
    hostname: security-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=agentmoby
      - MONGO_INITDB_ROOT_PASSWORD=secure_whale_2024
      - MONGO_INITDB_DATABASE=agentmoby_security
    volumes:
      - ./data/agentmoby:/docker-entrypoint-initdb.d:ro
      - security_db_data:/data/db
    networks:
      - security-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: [
      "mongod",
      "--quiet",
      "--logpath", "/var/log/mongodb/mongod.log",
      "--logappend"
    ]

  # Security Monitor - Watches for threats and anomalies
  security-monitor:
    build:
      context: .
      dockerfile: Dockerfile.security-monitor
    hostname: security-monitor
    environment:
      - SECURITY_DB_URI=mongodb://agentmoby:secure_whale_2024@security-db:27017/agentmoby_security?authSource=admin
      - ALERT_THRESHOLD=high
      - MONITORING_MODE=active
    depends_on:
      - security-db
    networks:
      - security-network
    restart: unless-stopped

networks:
  agentmoby-network:
    driver: bridge
    name: agentmoby_main
  security-network:
    driver: bridge
    name: agentmoby_security

volumes:
  security_db_data:
    name: agentmoby_security_data

configs:
  mcp_config:
    content: |
      mongodb:
        uri: mongodb://agentmoby:secure_whale_2024@security-db:27017/agentmoby_security?authSource=admin
      brave:
        endpoint: https://api.search.brave.com/res/v1/web/search
      resend:
        reply_to: security@agentmoby.com
        sender: alerts@agentmoby.com

secrets:
  openai-api-key:
    file: ./secret.openai-api-key
  mcp_secret:
    file: ./.mcp.env
