version: '3.8'

services:
  # Sock Store Frontend
  front-end:
    image: weaveworksdemos/front-end:0.3.12
    hostname: front-end
    ports:
      - "9090:8079"
    restart: unless-stopped
    cap_drop:
      - all
    read_only: true
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8079/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Catalogue Service
  catalogue:
    image: roberthouse224/catalogue:amd
    hostname: catalogue
    restart: unless-stopped
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    ports:
      - "8081:80"
    depends_on:
      catalogue-db:
        condition: service_healthy
    networks:
      - app-network
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Catalogue Database
  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    networks:
      - db-network
    volumes:
      - catalogue_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s

  # MongoDB for Customer Reviews
  mongodb:
    image: mongo:7-jammy
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=sockstore
    volumes:
      - ./data/mongodb:/docker-entrypoint-initdb.d:ro
      - mongodb_data:/data/db
    networks:
      - db-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    command: [
      "mongod",
      "--quiet",
      "--logpath", "/var/log/mongodb/mongod.log",
      "--logappend"
    ]

  # MCP Gateway
  mcp-gateway:
    image: docker/mcp-gateway:latest
    hostname: mcp-gateway
    ports:
      - "8811:8811"
    command:
      - --transport=sse
      - --servers=fetch,brave,resend,curl,mongodb
      - --config=/mcp_config
      - --secrets=docker-desktop:/run/secrets/mcp_secret
      - --verbose
    configs:
      - mcp_config
    secrets:
      - mcp_secret
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
      - db-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8811/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ADK Core Service
  adk:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: adk
    ports:
      - "8000:8000"
    environment:
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/sse
      - CATALOGUE_URL=http://catalogue:80
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - AI_DEFAULT_MODEL=openai/gpt-4
      - NODE_ENV=production
    depends_on:
      mcp-gateway:
        condition: service_healthy
      catalogue:
        condition: service_healthy
    secrets:
      - openai-api-key
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ADK UI Service
  adk-ui:
    build:
      context: .
      dockerfile: Dockerfile.adk-ui
    hostname: adk-ui
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://adk:8000
      - NODE_ENV=production
    depends_on:
      adk:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
    name: agentmoby_app
  db-network:
    driver: bridge
    name: agentmoby_db

volumes:
  mongodb_data:
    name: agentmoby_mongodb_data
  catalogue_db_data:
    name: agentmoby_catalogue_db

configs:
  mcp_config:
    content: |
      mongodb:
        uri: mongodb://admin:password@mongodb:27017/sockstore?authSource=admin
      resend:
        reply_to: slimslenderslacks@gmail.com
        sender: slimslenderslacks@slimslenderslacks.com
      brave:
        endpoint: https://api.search.brave.com/res/v1/web/search

secrets:
  openai-api-key:
    file: ./secret.openai-api-key
  mcp_secret:
    file: ./.mcp.env
