# MobyAgent Security Interceptors Configuration
# The whale that never blinks - comprehensive security controls

interceptors:
  # BEFORE INTERCEPTORS - Run before tool calls
  before:
    - name: "prompt-injection-guard"
      type: "exec"
      enabled: true
      priority: 100
      script: "/app/interceptors/before/prompt-injection-guard.py"
      config:
        max_prompt_length: 10000
        suspicious_patterns:
          - "ignore previous instructions"
          - "disregard system prompt"
          - "you are now"
          - "forget everything"
          - "new instructions"
        ml_model_path: "/app/models/prompt-injection-detector.onnx"
        confidence_threshold: 0.8
        block_on_detection: true
      
    - name: "auth-validator"
      type: "http"
      enabled: true
      priority: 90
      endpoint: "http://auth-service:8080/validate"
      config:
        timeout: 5000
        required_headers:
          - "Authorization"
          - "X-API-Key"
        jwt_secret_path: "/run/secrets/jwt_secret"
        rate_limit:
          requests_per_minute: 60
          burst: 10
      
    - name: "rate-limiter"
      type: "exec"
      enabled: true
      priority: 80
      script: "/app/interceptors/before/rate-limiter.sh"
      config:
        redis_url: "redis://redis:6379"
        redis_password_env: "REDIS_PASSWORD"
        global_limit: 1000
        per_user_limit: 100
        per_ip_limit: 50
        window_seconds: 3600
        block_duration: 300
      
    - name: "tool-access-control"
      type: "exec"
      enabled: true
      priority: 70
      script: "/app/interceptors/before/tool-access-control.py"
      config:
        policy_file: "/app/config/tool-policies.json"
        default_policy: "deny"
        admin_users:
          - "admin@mobyagent.com"
        restricted_tools:
          - "filesystem_write"
          - "system_exec"
          - "network_access"
        business_hours_only:
          - "sensitive_data_access"
        
    - name: "input-sanitizer"
      type: "exec"
      enabled: true
      priority: 60
      script: "/app/interceptors/before/input-sanitizer.py"
      config:
        max_input_size: 100000
        allowed_file_types:
          - "txt"
          - "json"
          - "yaml"
          - "md"
        scan_for_malware: true
        clamav_socket: "/var/run/clamav/clamd.ctl"
        block_executables: true
        filter_pii: true
        
  # AFTER INTERCEPTORS - Run after tool calls
  after:
    - name: "response-sanitizer"
      type: "exec"
      enabled: true
      priority: 100
      script: "/app/interceptors/after/response-sanitizer.py"
      config:
        remove_secrets: true
        secret_patterns:
          - "password"
          - "api_key"
          - "token"
          - "secret"
          - "private_key"
        redact_pii: true
        pii_patterns:
          - "email"
          - "phone"
          - "ssn"
          - "credit_card"
        max_response_size: 50000
        
    - name: "audit-logger"
      type: "http"
      enabled: true
      priority: 90
      endpoint: "http://wazuh-manager:55000/api/audit"
      config:
        timeout: 10000
        log_level: "info"
        include_request: true
        include_response: false  # Too large for audit
        include_user_context: true
        wazuh_auth_token_path: "/run/secrets/wazuh_token"
        
    - name: "secret-scanner"
      type: "exec"
      enabled: true
      priority: 80
      script: "/app/interceptors/after/secret-scanner.py"
      config:
        scan_response: true
        regex_patterns_file: "/app/config/secret-patterns.json"
        entropy_threshold: 4.5
        alert_on_detection: true
        webhook_url: "http://security-alerts:8080/secret-detected"
        
    - name: "anomaly-detector"
      type: "docker"
      enabled: true
      priority: 70
      image: "mobyagent/anomaly-detector:latest"
      config:
        model_path: "/models/anomaly-detection.pkl"
        features:
          - "response_time"
          - "response_size"
          - "tool_usage_pattern"
          - "user_behavior"
        threshold: 0.95
        learning_mode: false
        alert_webhook: "http://security-alerts:8080/anomaly-detected"
        
    - name: "compliance-checker"
      type: "exec"
      enabled: true
      priority: 60
      script: "/app/interceptors/after/compliance-checker.py"
      config:
        standards:
          - "SOC2"
          - "ISO27001"
          - "GDPR"
        data_classification:
          public: 0
          internal: 1
          confidential: 2
          restricted: 3
        retention_policies:
          public: 365
          internal: 180
          confidential: 90
          restricted: 30

# Global interceptor settings
global:
  timeout: 30000  # 30 seconds max per interceptor
  max_retries: 3
  backoff_multiplier: 2
  parallel_execution: false  # Security first, performance second
  fail_open: false  # Block on interceptor failure
  
  # Monitoring
  metrics:
    enabled: true
    endpoint: "http://prometheus:9090/metrics"
    labels:
      service: "mobyagent"
      component: "interceptor"
      
  # Logging
  logging:
    level: "info"
    format: "json"
    destinations:
      - "stdout"
      - "file:///var/log/interceptors/interceptor.log"
      - "syslog://wazuh-manager:514"
      
# Emergency controls
emergency:
  kill_switch:
    enabled: true
    triggers:
      - "too_many_prompt_injections"
      - "suspicious_tool_access"
      - "data_exfiltration_detected"
    actions:
      - "block_all_requests"
      - "alert_security_team"
      - "create_incident"
  
  circuit_breaker:
    enabled: true
    failure_threshold: 10
    timeout: 60000
    recovery_timeout: 300000
